### ISSUE TITLE
K rat placentas 2.0

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalAdmin#18]
Early planning stages, nothing to do yet

**Comment by gmyenni** [comment]
A more detailed explanation, just because it is cool:

Almost all rodents have “hemochorial” placentas, where the placenta (which is fetal tissue) invades into the wall of the uterus (maternal tissue) to the point that it breaks open maternal uterine blood vessels and causes maternal blood to wash into spaces made inside the placenta. So, in these species the blood of the mother leaves her circulatory system completely and comes into direct contact with fetal tissue. This is also what happens in humans.

There are two groups that are the exceptions: kangaroo rats and springhares. In these species, the placenta doesn’t invade very deeply so the maternal blood vessels do not break open, so there is no contact between maternal blood and fetal tissue (an “endotheliochorial” placenta). This has huge consequences on the physiology of pregnancy, i.e., no immune challenge to the mother because her blood is no longer exposed to paternal antigens on fetal tissues… but no ability on the part of the fetus to directly extract resources from mom so everything has to be transferred indirectly.

[Springhares are giant k-rats](http://media.web.britannica.com/eb-media/00/4400-004-1130EE83.jpg)!!: Desert environment, hopping gait. Adeptly named, they look like a cross between a giant k-rat and an actual hare. But springhares evolved these traits independently in Africa.

There is one species of rodent that has a hemochorial placenta as usual, but the placenta is missing many of the cell types which carry out invasion. It would seem to be a halfway house between the mouse kind of placenta and the kangaroo rat type of placenta. It is the [jerboa](http://channel.nationalgeographic.com/wild/destination-wild/videos/the-mini-kangaroo-of-the-sahara/), another adorable k-rat type thing that evolved independently from the others in Asia!

Researchers in human pregnancy and mouse pregnancy are super interested in finding out what is going on. Can they learn from them how to have healthy pregnancies in humans when things go wrong and the placenta does not invade enough? [Mick Elliot, St. John's College, Cambridge](http://www.michaelelliot.net/) wants to bring k-rats from Portal back to the lab to set up a breeding colony to study this.

**Comment by skmorgane** [comment]
Seems like this died so I'm going to close this issue
