### ISSUE TITLE
Reinstall phenocam

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalAdmin#2]
1. Use Ethernet switch to connect to modem and camera simultaneously
  2. Confirm camera is connected in StarDot Tools
  3. Go to camera's admin pages to view live image and confirm that image contains 20% sky/80% ground and is level (and doesn't have a black speck)

**Comment by gmyenni** [comment]
Apparently, first need to reconfigure camera before taking it into the field.
Does this make reinstalling it someone else's job next month, @bleds22e ?

**Comment by bleds22e** [comment]
Yeah, Joan’s. I’m going to reconfigure the camera next week. I’ll give Joan very specific instructions about how to do everything and promised I’d be “on call” that weekend.

On Jan 24, 2018, at 4:24 PM, Glenda <notifications@github.com<mailto:notifications@github.com>> wrote:


Apparently, first need to reconfigure camera before taking it into the field.
Does this make reinstalling it someone else's job next month, @bleds22e<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bleds22e&d=DwMCaQ&c=pZJPUDQ3SB9JplYbifm4nt2lEVG5pWx2KikqINpWlZM&r=xdViFy4bDJ4c_uqHNkTcvVR6J7re0HEWPL7vdHjIdQY&m=UYMdWFW5cc3wAZWBL9r5IPC1JyF4o4QNjWyTjK3vzaA&s=XzZ7yWMrCEJ2HtXWjozDehiIiMG8Mv92D_FmeGVcA_c&e=> ?

**Comment by gmyenni** [comment]
Okay. At least you can look at the image in the office and confirm there is no longer a black speck, before sending it back out into the field.

**Comment by bleds22e** [comment]
Phenocam is up and working, with no black dot. We will need to adjust it to get closer to a 20/80 sky/ground view, but at least it is taking clear pictures!

**Comment by gmyenni** [comment]
I saw that! It took a picture on Monday. But no more pictures since then. . .

**Comment by bleds22e** [comment]
Ummmmmmmmmm that's obnoxious
And highly confusing.

**Comment by gmyenni** [comment]
Done during #1 . Phenocam is configured and uploading photos, port forwarding configured.
